### ISSUE TITLE
0.2.1 issues

### ISSUE THREAD

**Issue by godarklight** [godarklight/DarkMultiPlayer#207]
This is a meta-bug to track ~~0.1.7~~ 0.2.1 targets.

- [ ] Fix docking - Possibly use lock-system to make sure dockings are deterministic.
- [x] ~~Fix a rotation bug, Likely a difference in vessel.terrainNormal.~~ I think we got this one.
- [ ] Fix the vessel altitude positioning bug, Needs vessel.PQSAltitude as the PQSTerrain does not seem to spawn accurately enough for our needs. EDIT: PQS seems to be mostly fine, something strange is going on here...
- [x] Bring back the Kerbal Rescue contracts.
- [x] Merge mod-support after we make sure it's useable and makes sense.
- [x] ~~Profile DMP to see if we can reduce lag. If possible, find an alternative to KillVessel/LoadVessel for vessel part replacements~~ - Don't think there is another way.
- [x] ~~Fix KillVessel from hanging the tracking station if we kill the selected vessel.~~ 0.90 fixed it :D
- [ ] Clicking on a player while in flight should target them, clicking on them in Tracking Station should ask to spectate.
- [ ] Groups.
- [ ] Vessel permissions.
- [ ] Shared career mode (#72, #164, #185, #226).
- [ ] Fix the EVA-Board hijack (#200)
- [ ] Fix the Docking to a future vessel bug with a warning first (#161/#120) - And if they dock anyway, Jump to the latest subspace, if the parts are the same, allow a docking. If not, eat it.
- [ ] Clean up the warp system - Use LockSystem for voting, skip inactive votes, Fix "Kicked for creating subspace" (#67/#68/#71).
- [x] IPv6 support (#76)
- [x] Plugin documentation
- [x] Hook up the server admin console to the client so you can /pm the server console commands. Player names are authenticated.
- [x] Secure player tokens server side, which means SHA256 hashing them at bare minimum. We might have to leave the token idea for security completely and go for public/private key pairs.
- [ ] GUI overhaul
- [ ] Fix HTTP server throwing on restart.

**Comment by godarklight** [comment]
I should stop doing these, they are useless :P

**Comment by oldmud0** [comment]
Yeah, you really need to start using milestones..
