### ISSUE TITLE
Current Issues

### ISSUE THREAD

**Issue by RockyTV** [godarklight/DarkMultiPlayer#373]
This is a list of current issues that are important and need to be fixed/implemented.

- [ ] Fix docking - Possibly use lock-system to make sure dockings are deterministic.
- [x] ~~Fix a rotation bug, Likely a difference in vessel.terrainNormal.~~ I think we got this one.
- [ ] Fix the vessel altitude positioning bug, Needs vessel.PQSAltitude as the PQSTerrain does not seem to spawn accurately enough for our needs. EDIT: PQS seems to be mostly fine, something strange is going on here...
- [x] Bring back the Kerbal Rescue contracts.
- [x] Merge mod-support after we make sure it's useable and makes sense.
- [x] ~~Profile DMP to see if we can reduce lag. If possible, find an alternative to KillVessel/LoadVessel for vessel part replacements~~ - Don't think there is another way.
- [x] ~~Fix KillVessel from hanging the tracking station if we kill the selected vessel.~~ 0.90 fixed it :D
- [ ] Clicking on a player while in flight should target them, clicking on them in Tracking Station should ask to spectate.
- [ ] Groups.
- [ ] Vessel permissions.
- [ ] Shared career mode (#72, #164, #185, #226).
- [ ] Fix the EVA-Board hijack (#200)
- [ ] Fix the Docking to a future vessel bug with a warning first (#161/#120) - And if they dock anyway, Jump to the latest subspace, if the parts are the same, allow a docking. If not, eat it.
- [ ] Clean up the warp system - Use LockSystem for voting, skip inactive votes, Fix "Kicked for creating subspace" (#67/#68/#71).
- [x] IPv6 support (#76)
- [x] Plugin documentation
- [x] Hook up the server admin console to the client so you can /pm the server console commands. Player names are authenticated.
- [x] Secure player tokens server side, which means SHA256 hashing them at bare minimum. We might have to leave the token idea for security completely and go for public/private key pairs.
- [ ] GUI overhaul
- [ ] Fix HTTP server throwing on restart.

**Comment by oldmud0** [comment]
Some of the issues you have linked are tagged low-priority, so it might be a bit misleading to mark this meta-issue as high-priority.

**Comment by RockyTV** [comment]
Doesn't it make sense to be tagged as high priority so one can take a look at what needs to be done?

**Comment by oldmud0** [comment]
Well, I consider "high priority" to mean that the issue should be fixed as soon as possible. If you want to keep it on top of the list, yeah I guess it makes sense.

**Comment by Scaprod** [comment]
and Live Feed issue, I elaborated on it.

**Comment by RacerXx** [comment]
"DaggerES' fork could fix it." This would prolly fix it. Problem is nobody is working on the "Core" problems. Last I heard they got vessel positioning fixed up to orbit. No REAL problem solving is being made in regards to docking and the "raytracing" landing problems

**Comment by oldmud0** [comment]
@RacerXx You should understand that devs are not paid anything at all to work on these projects. That makes a big difference because they must place priority on other things that do require their time and affect them in more significant ways.

**Comment by RockyTV** [comment]
The thing with mods is that you'll eventually lose interest in it sooner or later.

What @oldmud0 said is pretty much it. We have our real life to take care off. The problem with DMP is that it was "abandoned" (only critical updates are released) by @godarklight, the original author of DMP. Not only that, but we also don't have any incentive to work on the mod (and I don't mean money, because since the beginning darklight rejected any sort of donations and that kinda stuck around). There isn't a great amount of people playing DMP as of today.

And there's the matter of workarounds and trying to fix Squad's mess (there's a bunch of workarounds in the code and some stuff are overly complicated thanks to Squad!).

**Comment by godarklight** [comment]
To be fair KSP works around unity weirdness, it's a big chain of workarounds :D

**Comment by RacerXx** [comment]
I understand all that. But at the same time if nobody is interested or playing it is because OF the bugs. Thats why i stopped playing it. Then Luna came around and well that didnt get finished either. Im just tired of hearing the excuses and wish people would follow through. I am not referring to DMP in all this. Ive talked to dark I know what the issues are with DMP. I am referring to LUNA. They got it pretty much "Jitter free" up to orbit. Nice and smooth but then Lothsahn just got tired of doing it I guess. Its a shame to cause he was on a roll and if anybody could of made multiplayer happen after DMP it was him. Anyways Im out cya guys o7

**Comment by RockyTV** [comment]
He probably did it for the same reason as we did. Working alone on a big, ambitious project like this isn't fun or pleasing when you have little to zero incentive on doing it.

**Comment by Snoups58** [comment]
Hi, sorry for my bad english, i'm french.

I think i find when the lost reputation is effective:
I see the reputation move when, in the server, write :
"[DEBUG] Saving vessel xxxxxxxx from player" when player is another than me.

If it can help you ;)
